// services/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwtLrr4lKZ4IkdwU3dahZQYEZCe6yae-w',
    appId: '1:60743875957:web:bbe3f0acdb5a002f30673c',
    messagingSenderId: '60743875957',
    projectId: 'quizgame-2af7b',
    authDomain: 'quizgame-2af7b.firebaseapp.com',
    storageBucket: 'quizgame-2af7b.firebasestorage.app',
    measurementId: 'G-325Y2N7C9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-4DS0OcjaPQlKaxwrdug6q_uo0JUtKtI',
    appId: '1:60743875957:android:d007457bf62a630b30673c',
    messagingSenderId: '60743875957',
    projectId: 'quizgame-2af7b',
    storageBucket: 'quizgame-2af7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0HHTzPLM9YgiOyNJtQ9vxrl1cmL4734',
    appId: '1:60743875957:ios:7ddd55b9da44229b30673c',
    messagingSenderId: '60743875957',
    projectId: 'quizgame-2af7b',
    storageBucket: 'quizgame-2af7b.firebasestorage.app',
    iosClientId: '674029223791-eoi7qsf1mq9q6djr6ku6jgc84q0rcmaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
